title: MAF 261
description: Página da disciplina de Estatística Experimental oferecida a alunos da UFV - Campus Florestal

url: https://github.com/maf261
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Cronograma
   url: /cronograma
 - title: Contato
   url: /contato
 - title: Aulas
   url: /aulas
 - title: Exercícios
   url: /exercicios
 - title: Materiais
   url: /materiais
 - title: Créditos
   url: /creditos

social:
   github: maf261
   twitter: 
   facebook: 
   email: ufv.florestal.maf261@gmail.com

google_analytics: "UA-58263416-1"
